language: java
jdk:
  - openjdk8

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean build
  #  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t $DOCKER_REGISTRY/app/test-ci:0.0.1 .
  - docker push $DOCKER_REGISTRY/app/test-ci:0.0.1
# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - "xiah0526@gmail.com"