version: '3.2'
services:
  app:
    image:
    build: .
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - TZ=Asia/Seoul
    ports:
      - 80:9090
    depends_on:
      - db
  db:
    image: postgres:12.6
    volumes:
      - db-data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=mycat
      - POSTGRES_PASSWORD=admin
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
      - TZ=Asia/Seoul
      - LC_COLLATE=C
    ports:
      - 5432:5432
volumes:
  db-data:
